trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - v*

stages:
  - stage: continuous_integration
    displayName: 'Build and test'
    pool:
      name: 'AWS EC2 Pool'
    jobs:
      - job: Build
        displayName: 'Build, test, pack and push'
        steps:
          - task: AWSShellScript@1
            displayName: 'Build, test and pack'
            inputs:
              arguments: 'Pack'
              filePath: './build.cmd'
              scriptType: 'filePath'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'Cos'
          - task: DotNetCoreCLI@2
            displayName: 'Push NuGet package'
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
            inputs:
              command: 'custom'
              arguments: 'push --skip-duplicate'
              searchPatternPush: '$(Build.ArtifactStagingDirectory)/**/Cos*.nupkg'
              feedPublish: 'costest2'