trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - v*

stages:
  - stage: continuous_integration
    displayName: 'Build and test'
    pool:
      name: 'AWS EC2 Pool'
    jobs:
      - job: Build
        displayName: 'Build and test'
        steps:
          - task: AWSShellScript@1
            displayName: 'Build, test and pack'
            inputs:
              arguments: 'Pack'
              filePath: './build.cmd'
              scriptType: 'filePath'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'Cos'
  - stage: 'PublishNuGetPackage'
    displayName: 'Publish NuGet Package'
    dependsOn: 'continuous_integration'
    pool: 'AWS EC2 Pool'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    jobs:
    - job:
      displayName: 'Push NuGet package'
      steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        artifact: 'Cos'
        path: '$(Pipeline.Workspace)/artifacts'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'push'
          searchPatternPush: '$(Pipeline.Workspace)/artifacts/**/Cos*.nupkg'
          feedPublish: 'easee-norway'