stages:
  - stage: continuous_integration
    displayName: 'Build and test'
    dependsOn: []
    pool:
      name: 'AWS EC2 Pool'
    variables:
      buildConfiguration: 'Release'
    jobs:
      - job: Build
        displayName: 'Build and test'
        dependsOn: []
        steps:
          - task: DotNetCoreCLI@2
            displayName: Build and Test
            inputs:
              arguments: 'Test'
              filePath: './build.cmd'
          - publish: 'artifacts'
            artifact: 'package'
  - stage: 'PublishNuGetPackage'
    displayName: 'Publish NuGet Package'
    dependsOn: 'continuous_integration'
    pool: 'AWS EC2 Pool'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/feature/nuget'))
    jobs:
    - job:
      displayName: 'Push NuGet package'
      steps:
      - checkout: none
      - task: NuGetCommand@2
        displayName: 'Push NuGet Package'
        inputs:
          arguments: 'PublishNuGetPackage'
          filePath: './build.cmd'