trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

stages:
  - stage: continuous_integration
    displayName: 'Build and test'
    pool:
      name: 'AWS EC2 Pool'
    jobs:
      - job: Build
        displayName: 'Build, test, pack and push'
        steps:
          - task: AWSShellScript@1
            displayName: 'Build, test and pack'
            inputs:
              arguments: 'Pack'
              filePath: './build.cmd'
              scriptType: 'filePath'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'Cos'
          - task: AWSShellScript@1
            displayName: 'Push to NuGet feed'
            inputs:
              arguments: 'Push'
              filePath: './build.cmd'
              scriptType: 'filePath'