stages:
  - stage: continuous_integration
    displayName: 'Build and test'
    pool:
      name: 'Azure Pipelines'
    jobs:
      - job: Build
        displayName: 'Build and test'
        steps:
          - task: ShellScript@2
            displayName: 'Build, test and pack'
            inputs:
              scriptPath: './build.sh'
              args: 'CreateNuGetPackage'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/artifacts'
          - task: ShellScript@2
            displayName: 'Push NuGet Package'
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/feature/nuget'))
            inputs:
              scriptPath: './build.sh'
              args: 'PushNuGetPackage'
