stages:
  - stage: continuous_integration
    displayName: 'Build and test'
    pool:
      name: 'AWS EC2 Pool'
    jobs:
      - job: Build
        displayName: 'Build and test'
        steps:
          - task: AWSShellScript@1
            displayName: 'Build, test and pack'
            inputs:
              arguments: 'CreateNuGetPackage'
              filePath: './build.cmd'
              scriptType: 'filePath'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/artifacts'
  - stage: 'PublishNuGetPackage'
    displayName: 'Publish NuGet Package'
    dependsOn: 'continuous_integration'
    pool: 'AWS EC2 Pool'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/feature/nuget'))
    jobs:
    - job:
      displayName: 'Push NuGet package'
      steps:
      - task: NuGetCommand@2
        displayName: 'Deploy to NuGet feed'
        inputs:
          command: 'push'
          packagesToPush: '$(Pipeline.Workspace)/artifacts/**/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: 'https://pkgs.dev.azure.com/easee-norway/_packaging/easee-norway/nuget/v3/index.json'