on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/easee/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_READ_PAT_JANERIKFOSS }}

      - name: Build
        run: dotnet build ./Cos.sln --configuration Release

      - name: Test
        run: dotnet test ./Cos.sln --configuration Release --no-build
