on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify commit exists in origin/main
        run: git branch --remote --contains | grep origin/main

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/easee/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_READ_PAT_JANERIKFOSS }}

      - name: Build
        run: dotnet build ./Cos.sln --configuration Release /p:Version=${VERSION}

      - name: Test
        run: dotnet test ./Cos.sln --configuration Release /p:Version=${VERSION} --no-build

      - name: Pack
        run: dotnet pack ./Cos/Cos.csproj --configuration Release /p:Version=${VERSION} --no-build --output .

      - name: Push
        run: dotnet nuget push Easee.Cos.${VERSION}.nupkg --source https://nuget.pkg.github.com/easee/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
