on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: src
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Verify commit exists in origin/main
      run: git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build ./Cos.sln --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test ./Cos.sln --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack ./Cos/Cos.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push NuGet.Workflow.${VERSION}.nupkg --source https://pkgs.dev.azure.com/easee-norway/_packaging/costest2/nuget/v3/index.json